### ISSUE TITLE
Canary plug in is breaking the styling in Markdown 

### ISSUE THREAD

**Issue by Duke-Box** [jcwillox/lovelace-canary#1]
Hi,

I have a Markdown card with a config of:

'''
    cards:
      - type: markdown
        style: |
          ha-card {
            padding: 31px;
          }
          h1 {
            text-align: center;
            font-size: 90px;
          }
          h2 {
            text-align: center;
            color: var(--primary-color);
          }
        content: |
          # {{ states('sensor.local_time')}} 
          ## {{ states('sensor.local_date')}}
'''
which gives this:

![B4_Canary](https://user-images.githubusercontent.com/38861692/77009373-b3593900-695f-11ea-8bed-d5c6ecf7ed45.PNG)

When I install Canary and load the module in the lovelace YAML, the Markdown looks like this:

![After_Canary](https://user-images.githubusercontent.com/38861692/77009804-780b3a00-6960-11ea-8241-39ce9a346967.PNG)

It appears that Canary is affecting the CSS styling in the Markdown card.

I am running Home Assistant (Hassio) 106.6

Thanks 
Mike

**Comment by jcwillox** [comment]
Hey, based on the configuration above Canary will never touch the markdown card.
What are you using to style the markdown card, the core [markdown card](https://www.home-assistant.io/lovelace/markdown/) does not support styling?

Also, to format your code use ``` three backticks.

**Comment by bieniu** [comment]
I have the same issue but with other cards (sensor, entities, glance). Most of my styling from `card-mod` don't work when `canary` is loaded. For example:
```yaml
             - type: sensor
                entity: sensor.airly_info
                style: |
                  ha-card {
                    background:
                      {% set airly = states("sensor.airly_info") %}
                      {% if airly == "bardzo dobra" %}
                        #43a047
                      {% elif airly == "dobra" %}
                        #fbc02d
                      {% elif airly == "średnia" %}
                        #fb8c00
                      {% elif airly == "zła" %}
                        #f4511e
                      {% elif airly == "bardzo zła" %}
                        #d81b60
                      {% else %}
                        #000000;
                      {% endif %};
                    color: #fff;
                  }
                  ha-icon {
                    color: #ffffff;
                  }
```
