### ISSUE TITLE
'no_card: true' don‘t work with 'in_card: true' in vertical-stack

### ISSUE THREAD

**Issue by Krocko** [jcwillox/lovelace-canary#14]
The option `no_card: true` don‘t work in a vertical-stack card if set `in_card: true` also.

**Comment by jcwillox** [comment]
Hmm, I suppose I could include that ability, you could always add `no_card: true` to the inner cards to hide their backgrounds, and you can probably use `canary_style` to adjust to card spacing.

```yaml
type: vertical-stack
title: Hello
cards:
  - type: entities
    title: Lights
    no_card: true
    entities:
      - entity: light.bedroom_light
        secondary_info:
          entity: light.bedroom_underglow
          prefix: 'The Underglow is '
  - type: entities  
    title: Lights
    no_card: true
    entities:
      - light.bedroom_underglow
```
The reason it doesn't just work implicitly is that the `no_card` option only works and cards that use the `ha-card` element, e.g. the `entities` card, `vertical-stack` cards do not use `ha-card` even when using `in_card: true`.

**Comment by Krocko** [comment]
Thank you, for your help. 
I have `no_card: true` on the inner cards. But this don't work also. 
Can you please explain how to use this `canary_style`?

**Comment by jcwillox** [comment]
Can you provide an example config to demonstrate the issue you're having?

I've updated the example above to include an example of `canary_style`, there's also some more info in the [docs](https://github.com/jcwillox/lovelace-canary/wiki/Generic-Card#canary_style).

```yaml
canary_style:
  margin-top: -24px;
```

**Comment by Krocko** [comment]
```
  - type: vertical-stack
    in_card: true
    cards:
      - type: markdown
        no_card: true
        content: >-
          ## <center><font color= '#FF8300'>bla bla bla</font></center>
      - type: markdown
        no_card: true
        content: Some Text
      - type: markdown
        no_card: true
        content: Some Value
```
![image](https://user-images.githubusercontent.com/29394115/108488245-6fbe2c00-72a0-11eb-845e-0fb0d09af3f9.jpeg)

**Comment by jcwillox** [comment]
Ahhh, I made the mistake of testing on my development version, you're correct `canary_style` does not work correctly in the currently released version. I'll release a fixed version shortly.

**Comment by Krocko** [comment]
Thank you very much!

**Comment by jcwillox** [comment]
This should be fixed in [0.3.2](https://github.com/jcwillox/lovelace-canary/releases/tag/0.3.2), let me know if it's working now.

**Comment by Krocko** [comment]
It is still the same problem with 0.3.2

**Comment by jcwillox** [comment]
Did you make sure you're running the new version, it will show which version you are running in the browser console. In that image you sent, `no_card` is working, and I can confirm that after copy and pasting the second example you sent `canary_style` is working correctly in 0.3.2.

**Comment by Krocko** [comment]
Yes, the latest version is installed.

**Comment by jcwillox** [comment]
Hmm, well I'm not sure what's happening then, this is what I get. 
![image](https://user-images.githubusercontent.com/39120423/108513845-3a085a00-7317-11eb-99b5-19f3c0a90708.png)

Does `canary_style` not work in any way, e.g. trying to change text color?
```yaml
canary_style:
  margin-top: '-24px;'
  color: red
```
