### ISSUE TITLE
Canary doesn't work with HA 2021.6

### ISSUE THREAD

**Issue by bieniu** [jcwillox/lovelace-canary#16]
Card configuration:
```yaml
      - type: vertical-stack
        in_card: true
        cards:
          - type: glance
            title: "Salon"
            show_name: false
            entities:
              - sensor.temperature_salon
              - sensor.humidity_salon
              - sensor.co2_salon
              - sensor.illumination_salon
          - type: entities
            show_header_toggle: false
            state_color: true
            entities:
              - binary_sensor.window_salon
              - entity: binary_sensor.motion_salon
```

I think this problem is related to this https://developers.home-assistant.io/blog/2021/05/19/lit-2.0

Console error:
```
app.cdb4df30.js:13498 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
55704 @ app.cdb4df30.js:13498
s @ app.cdb4df30.js:36059
53918 @ app.cdb4df30.js:7396
s @ app.cdb4df30.js:36059
(anonymous) @ app.cdb4df30.js:36059
(anonymous) @ app.cdb4df30.js:42171
(anonymous) @ app.cdb4df30.js:42171
canary.js:1  CANARY  0.3.3 
canary.js:1 Uncaught (in promise) TypeError: customElements.get(...).getStyles is not a function
    at canary.js:1
(anonymous) @ canary.js:1
Promise.then (async)
(anonymous) @ canary.js:1
n @ canary.js:1
(anonymous) @ canary.js:1
(anonymous) @ canary.js:1
```
