### ISSUE TITLE
secondary_info with 

### ISSUE THREAD

**Issue by cyberjacob** [jcwillox/lovelace-canary#17]
Hi, is it possible to use a `secondary_info` with an entity card?

For example:
```yaml
type: entity
entity: sensor.daily_energy
name: Energy Usage Today
secondary_info: Enough to charge {{ states('sensor.daily_energy') }} phones
```
