### ISSUE TITLE
Include A/C Example in docs

### ISSUE THREAD

**Issue by johntdyer** [jcwillox/lovelace-canary#2]
I love the look of this card

<img width="871" alt="image" src="https://user-images.githubusercontent.com/58234/77128918-668d6500-6a28-11ea-8132-620c957b2c6a.png">

can you please include the yaml used to generate it as the example ?

**Comment by jcwillox** [comment]
Yeah, sure I'll add it as a show more option. Here's the full config 👍.
```yaml
type: 'custom:canary-card'
theme: simple-thermostat
card:
  type: vertical-stack
  in_card: true
  cards:
    - type: 'custom:simple-thermostat'
      no_card: true
      entity: climate.bedroom_aircon
      decimals: 1
      sensors:
        - attribute: current_humidity
          name: Humidity
          unit: ' %'
      step_size: 1
      control:
        _headings: false
        fan:
          auto:
            icon: false
          high:
            name: High
          low:
            name: Low
          medium:
            name: Med
        hvac:
          dry: false
          auto:
            name: false
          cool:
            name: false
          fan_only:
            name: false
          'off':
            name: false

    - type: entities
      no_card: true
      entities:
        - type: 'custom:paper-buttons-row'
          buttons:
            - entity: light.bedroom_aircon_light
              icon: 'mdi:lightbulb'
              name: Light
              state_icons:
                'off': 'mdi:lightbulb-off-outline'
                'on': 'mdi:lightbulb'
              tap_action:
                action: toggle

            - entity: input_boolean.bedroom_swing_mode
              icon: 'mdi:repeat'
              name: Swing
              state_icons:
                'off': 'mdi:repeat-off'
                'on': 'mdi:repeat'
              tap_action:
                action: toggle

            - entity: input_boolean.enable_aircon_controller
              icon: 'mdi:remote'
              name: false
              state_icons:
                'off': 'mdi:remote-off'
                'on': 'mdi:remote'
              state_styles:
                'off':
                  button:
                    color: var(--primary-background-color)
                'on':
                  button:
                    color: var(--primary-text-color)
              tap_action:
                action: toggle
```

The localized theme I'm using, this is added on top of my base theme. This allows me to still update my base theme with HACS, if I included it in the base theme it would get overwritten when updating.
```yaml
simple-thermostat:
  st-mode-background: "var(--table-row-alternative-background-color)"
```
