### ISSUE TITLE
Custom custom:canary-card doesn't work as expected

### ISSUE THREAD

**Issue by cadavre** [jcwillox/lovelace-canary#22]
### The problem

If `canary` is not loaded into browser resources yet – styles are not applied. Fresh loads, without cached assets, always causes `style` not being applied to the card. This is expected. Another refresh (without cache clearing) makes cards looks good, with styles applied. (Look more details below.)

To solve this issue I guess that `custom:canary-card` was introduced. Unfortunately this card doesn't work as expected, producing:

<img width="227" alt="Zrzut ekranu 2022-12-29 o 15 21 29" src="https://user-images.githubusercontent.com/461796/209966937-ea55b4ae-d2c5-4bf9-ad7c-13145adb40a0.png">

### What version of Canary has the issue?

0.4.0

### What version of Home Assistant are you running?

2022.12.8

### What version of the Frontend are you running?

20221213.1 - latest

### Example YAML snippet

```yml
I have a complex vertical-stack like this:


type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: ...
        ...
        style: |
          ...
      - type: custom:mini-graph-card
        entities:
          - entity: ...
        ...
        style: |
          ...
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: ...
        ...
        style: |
          ...
      - type: custom:mini-graph-card
        entities:
          - entity: ...
        ...
        style: |
          ...
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: ...
        ...
        style: |
          ...
      - type: custom:mini-graph-card
        entities:
          - entity: ...
        ...
        style: |
          ...
```

### Additional information

Without `custom:canary-card`.

### Fresh load:
<img width="498" alt="Zrzut ekranu 2022-12-29 o 15 16 18" src="https://user-images.githubusercontent.com/461796/209967186-5beaae25-66c4-459c-845e-ff1d6fe6b075.png">

### After refresh:
<img width="473" alt="Zrzut ekranu 2022-12-29 o 15 16 23" src="https://user-images.githubusercontent.com/461796/209967215-f0dec67a-f5b6-48ef-b2b8-98d4d94aa9d2.png">

**Comment by birdwing** [comment]
I get the exact same issue you are seeing.

```yaml
type: custom:canary-card
card:
  type: vertical-stack
  in_card: true
  cards:
    - show_current: true
      show_forecast: false
      type: weather-forecast
      entity: weather.tomorrow_io_the_browns_daily
      no_card: true
    - type: entities
      entities:
        - type: section
          label: Weekly Forecast
      show_header_toggle: false
    - show_current: false
      show_forecast: true
      type: weather-forecast
      entity: weather.tomorrow_io_the_browns_daily
    - type: entities
      entities:
        - type: section
          label: Hourly Forecast
      show_header_toggle: false
    - show_current: false
      show_forecast: true
      type: weather-forecast
      entity: weather.tomorrow_io_the_browns_hourly
```

If I edit the card in the dashboard by adding and removing a space ( not making any actual changes just need the save button to work) the error goes away, until the next time I open home assistant, then it's broken again.

**Comment by birdwing** [comment]
I have found a somewhat annoying workaround.
If you near the canary-card within another canary-card the issue goes away.

It appears that the issue is related to an "in_card" not being loaded when canary-card runs.

So this works for me (same card just double canary-card)

```yaml
type: custom:canary-card
card:
  type: custom:canary-card
  card:
    type: vertical-stack
    in_card: true
    cards:
      - show_current: true
        show_forecast: false
        type: weather-forecast
        entity: weather.tomorrow_io_the_browns_daily
        no_card: true
      - type: entities
        entities:
          - type: section
            label: Weekly Forecast
        show_header_toggle: false
      - show_current: false
        show_forecast: true
        type: weather-forecast
        entity: weather.tomorrow_io_the_browns_daily
      - type: entities
        entities:
          - type: section
            label: Hourly Forecast
        show_header_toggle: false
      - show_current: false
        show_forecast: true
        type: weather-forecast
        entity: weather.tomorrow_io_the_browns_hourly
```
