### ISSUE TITLE
Not working with (mushroom) entity cards

### ISSUE THREAD

**Issue by SamDT92** [jcwillox/lovelace-canary#25]
### The problem

I can't seem to get this working with any single entity card, default lovelace or mushroom.

I'm trying to display a card that acts as a button for lights in the room.
Below the icon, I would like to show the room temperature, but whenever I try to add my temperature sensor as secondary I get this error: Key "secondary_info" is not expected or supported by the visual editor.

I've tried all secondary info objectThomas Lovén's templates or Jinja2 templates, but none seem to work.
When copy pasting an example from GitHub, it does work, so the integration seems to be installed and working correctly.

Is this intended to not work or am I missing something?

### What version of Canary has the issue?

0.4.0

### What version of Home Assistant are you running?

Home Assistant 2023.2.5

### What version of the Frontend are you running?

Frontend-versie: 20230202.0 - latest

### Example YAML snippet

```yml
type: entity
entity: light.living
secondary_info: "{{ sensor.luchtkwaliteits_monitor_temperature }}"

type: custom:mushroom-entity-card
entity: light.living
layout: vertical
secondary_info: "{{ sensor.luchtkwaliteits_monitor_temperature }}"
```
