### ISSUE TITLE
Strange shadow with in_card: true option

### ISSUE THREAD

**Issue by bieniu** [jcwillox/lovelace-canary#3]
In my configuration I stack `entities` and `glance` cards with the `in_card: true` option. When there is `input_select` or `custom:mini-media-player` card in the `entities` card something strange happens with the shadow:

![image](https://user-images.githubusercontent.com/478555/79064973-773e9d00-7cad-11ea-917c-2fbf3b8330b0.png)

My config:
```yaml
- type: vertical-stack
  in_card: true
  cards:
    - type: glance
      title: "Salon"
      show_name: false
      entities:
        - sensor.temperature_salon
        - sensor.humidity_salon
        - sensor.co2_salon
        - sensor.illumination_salon
    - type: entities
      show_header_toggle: false
      state_color: true
      entities:
        - entity: binary_sensor.motion_salon
          secondary_info: last-changed
        - climate.thermostat_salon
        - fan.humidifier_salon
        - light.bulbs_salon
        - light.leds_salon
        - light.lamp_salon
        - input_select.light_scenes_salon
        - input_select.salon_harmony
        - type: custom:mini-media-player
          entity: media_player.bravia
          hide:
            controls: true
            volume: true
            power: true
            progress: true
          info: scroll
          group: true
        - type: custom:mini-media-player
          entity: media_player.denon
          hide:
            controls: true
            volume: true
            mute: true
            power: true
            power_state: false
            progress: true
          info: scroll
          group: true
        - type: custom:mini-media-player
          entity: media_player.playstation
          hide:
            controls: true
            volume: true
            power: true
            progress: true
            source: true
          info: scroll
          group: true
        - type: custom:mini-media-player
          entity: media_player.echo_show
          hide:
            controls: true
            volume: true
            power: true
            progress: true
          info: scroll
          group: true
```

**Comment by jcwillox** [comment]
Yep, this is an issue with the `in_card` extension it doesn't seem to reliably remove the card background. I'll try to implement a more stable version when I get the chance. 
Currently, the remedy to this is to manually remove the card backgrounds. To do this use the [`no_card`](https://github.com/jcwillox/lovelace-canary#no_card) extension on primarily the `entities` card and also the `glance` card. 

This should hopefully fix that for now 👍 .
```yaml
- type: vertical-stack
  in_card: true
  cards:
    - type: glance
      title: "Salon"
      no_card: true
      ...

    - type: entities
      show_header_toggle: false
      state_color: true
      no_card: true
      ...
```

**Comment by bieniu** [comment]
Sorry for the delay. In fact, `no_card: true` has fixed the issue. But now when I reload a page I have something like this:

![vertical-stack](https://user-images.githubusercontent.com/478555/79422260-da397800-7fbc-11ea-909f-3c3163bbb606.gif)

Is there a way to remove this "animated" joining the cards?

**Comment by bieniu** [comment]
When I use `custom:canary-card` effect is better but not ideal.
```yaml
- type: custom:canary-card
  card:
    type: vertical-stack
    in_card: true
    cards:
      - type: glance
        title: "Salon"
        no_card: true
        ...

      - type: entities
        show_header_toggle: false
        state_color: true
        no_card: true
        ...
```
