### ISSUE TITLE
canary breaks last-update in secondary_info

### ISSUE THREAD

**Issue by erkr** [jcwillox/lovelace-canary#36]
### The problem

Thanks for this great frontend extension !! Small issue. Since  I installed canary, secondary_info: last-updated is broken. Note: last-changed works fine:
``` 
type: entities
entities:
      - entity: sensor.actual_power
        name: Actueel Stroom verbruik
        secondary_info: last-updated
``` 
Results in:
<img width="375" alt="image" src="https://github.com/jcwillox/lovelace-canary/assets/4363599/d349735f-6a35-45b4-a794-4c704eee92f9">

best Eric

### What version of Canary has the issue?

0.4.0

### What version of Home Assistant are you running?

Core-2023.6.3

### What version of the Frontend are you running?

20230608.0

### Additional information

When I add:
`    disable_canary: secondary_info`
It works
