### ISSUE TITLE
Nothing appearing

### ISSUE THREAD

**Issue by alphabeta279** [jcwillox/lovelace-canary#4]
Pretty sure I'm misunderstanding this, but nothing appears to be visible with this code:

```
entities:
  - entity: vacuum.roomba
    image: \local\images\roomba980.png
    secondary_info:
      attribute: vacuum.roomba.battery-level
      prefix: "Battery: "
      postfix: "%"
  - entity: vacuum.roobot
    image: \local\images\deebot.png
    secondary_info: last-changed
title: Robot Vacuums
type: entities

```
Can anyone point out what I'm doing wrong here? It's working fine without this part:

```
    secondary_info:
      attribute: vacuum.roomba.battery-level
      prefix: "Battery: "
      postfix: "%"
```
