### ISSUE TITLE
Chrome compatibility on card background

### ISSUE THREAD

**Issue by sephrioth** [jcwillox/lovelace-canary#58]
### The problem

The cards background(with opacity) overlaps each other on Chrome (macOS 14.2.1), but display correctly in Safari.

I tried to use no_card method, but it doesn't work properly(error be like: Key 'entities.0.type' is not expected or not supported ).

Chrome:
<img width="322" alt="image" src="https://github.com/jcwillox/lovelace-canary/assets/4231328/9b669b43-24a0-4978-a8e6-f6a4699f7f52">
 
Safari:
<img width="322" alt="image" src="https://github.com/jcwillox/lovelace-canary/assets/4231328/68e2fc42-c5d3-4d3d-8226-04539f3ef049">

### What version of Canary has the issue?

0.4.0

### What version of Home Assistant are you running?

2024.5.3

### What version of the Frontend are you running?

20240501.1

### Example YAML snippet

```yml
cards:
  - type: glance
    entities:
      - entity: sensor.kitchen_temperature
        secondary_info: last-changed
      - entity: sensor.kitchen_humidity
        secondary_info: last-changed
      - entity: binary_sensor.kitchen_waterleak
        secondary_info: last-changed
      - entity: sensor.kitchen_cooker_status
        secondary_info: last-changed
    columns: 4
  - type: entities
    entities:
      - entity: binary_sensor.kitchen_motion_sensor
        secondary_info: last-changed
      - entity: light.kitchen_lights
        secondary_info: last-changed
      - entity: select.kitchen_cooker_mode
    show_header_toggle: false
title: 🍳 Kitchen
type: vertical-stack
in_card: true
```
