### ISSUE TITLE
Add templating ability to entity name

### ISSUE THREAD

**Issue by regystro** [jcwillox/lovelace-canary#7]
Hi.

Would it be possible to add the same templating capabilities like in [secondary_info](https://github.com/jcwillox/lovelace-canary/wiki/Generic-Entity-Row#secondary_info) for the entities name?

I know I can customize the friendly_name in Lovelace, but that wouldn't work for dynamical entities like the ones generated by this integration: https://www.home-assistant.io/integrations/seventeentrack/

And something like
```
type: entities
title: Parcel
entities:
  - entity: sensor.seventeentrack_package_tracknumber1
    name: >-
      {{ state_attr(entity,'friendly_name') | regex_replace(find='Seventeentrack
      Package: ', replace='', ignorecase=True) }}
    secondary_info: 'Status: {{ state_attr(entity,''info_text'') | upper }}'
  - entity: sensor.seventeentrack_package_tracknumber2
```
would be awesome, specially if used in conjunction with Thomas Lovén's auto-entities to auto populate all trackings at once.

Thank you and greetings.
