### ISSUE TITLE
[FR]: Support for templating in Entities Card for `icon`

### ISSUE THREAD

**Issue by jeremysherriff** [jcwillox/lovelace-canary#70]
### Is your feature request related to a problem? Please describe.

I'd like to be able to override icons in a dynamic way.

### Describe the solution you'd like

To be able to include templating in the `icon` value for generic Entities cards:
```
type: entities
title: Parcel
entities:
  - entity: sensor.seventeentrack_package_tracknumber1
    secondary_info: 'Status: {{ state_attr(entity,''info_text'') | upper }}'
    icon: {{ "mdi:party-popper" if is_state_attr(entity,''info_text'',"delivered") else "mdi:truck" }}
  - entity: sensor.seventeentrack_package_tracknumber2
```

### Describe alternatives you've considered

Creating a template sensor with the icon, state etc
