### ISSUE TITLE
in_card does not work when the refreshed page displays vertical-stack

### ISSUE THREAD

**Issue by Arubinu** [jcwillox/lovelace-canary#72]
### The problem

As the title explains, if the page displayed when loading is the one that contains the vertical-stack with in_card, it behaves like a classic vertical-stack:
![Image](https://github.com/user-attachments/assets/6c3c31bc-8067-48be-949a-801479657d70)

On the other hand, if I am on another Home Assistant page or even another Dashboard tab, once I arrive where this card is displayed, it works perfectly:
![Image](https://github.com/user-attachments/assets/6292f5bb-d44c-44a7-9119-8f65ac441427)

### What version of Canary has the issue?

v0.5.0

### What version of Home Assistant are you running?

2025.3.4

### What version of the Frontend are you running?

20250306.0

### Example YAML snippet

```yml
type: vertical-stack
in_card: true
state_color: true
cards:
  - type: tile
    entity: switch.one
    icon: mdi:door-open
    state_content: last_changed
    features_position: inline
    vertical: false
    grid_options:
      columns: full
    features:
      - type: toggle
  - type: tile
    entity: switch.two
    state_content: last_changed
    features_position: inline
    vertical: false
    grid_options:
      columns: full
    features:
      - type: toggle
  - type: tile
    entity: switch.three
    state_content: last_changed
    features_position: inline
    vertical: false
    grid_options:
      columns: full
    features:
      - type: toggle
```

### Anything in the logs that might be useful for us?

```python3
The following line (the first therefore) is only displayed when I refresh the cache:
Error with Permissions-Policy header: Unrecognized feature: 'browsing-topics'.

canary.js?hacstag=245159052050:1029  CANARY  0.5.0 
canary.js?hacstag=245159052050:1033 branch   : main
canary.js?hacstag=245159052050:1033 commit   : 2033b59ebec12f30d132962907a413d3e84d5a12
canary.js?hacstag=245159052050:1033 built at : 2024-07-28T04:51:28.963Z
canary.js?hacstag=245159052050:1033 https://github.com/jcwillox/lovelace-canary

canary.js?hacstag=245159052050:1048 You may not be getting optimal performance out of canary.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
```

### Additional information

I added card-mod to my configuration file (installed via HACS):
CARD-MOD 3.4.4 IS INSTALLED
