### ISSUE TITLE
Vertical stack with horizontal-stacks

### ISSUE THREAD

**Issue by PierreScerri** [jcwillox/lovelace-canary#9]
The image below shows a vertical stack containing 8 horizontal stacks of buttons and 2 custom:bar-cards.

![Screenshot 2020-08-14 at 11 08 24](https://user-images.githubusercontent.com/34303331/90233794-f5a77900-de1e-11ea-8eec-8cf9a9105698.png)

When I add:

in_card: true

I get:

![Screenshot 2020-08-14 at 11 09 03](https://user-images.githubusercontent.com/34303331/90233796-f6d8a600-de1e-11ea-95cf-e0e47d3f8254.png)

**Comment by zen2** [comment]
I got a similar problem but without horizontal-stack.
In my case it's several vertical-stack inside a vertical-stack using "the in-card: true":

```
 - type: vertical-stack
    in_card: true
    cards:
    - type: vertical-stack
      cards:
      ....
    - type: vertical-stack
      cards:
      ....
    - type: vertical-stack
      cards:
      ....
```

Without in-card option, spaces are perfect:
![without](https://user-images.githubusercontent.com/9433239/90315965-d8a69f00-df1f-11ea-8b91-645c3f56ffa5.png)

Whit in-card option, there is overlapping:
![with-in-card](https://user-images.githubusercontent.com/9433239/90315970-df351680-df1f-11ea-9838-968a30f62d5d.png)

So it seems that the vertical spacing is messed up when we use several level of vertical-stack or horizontal-stack with in-card option set to the top level.
